FROM node:18-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ARG PORT
ARG MONGO_URI
ARG JWT_SECRET
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET

ENV PORT=$PORT \
    MONGO_URI=$MONGO_URI \
    JWT_SECRET=$JWT_SECRET \
    CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

RUN echo "PORT=$PORT" >> .env && \
    echo "MONGO_URI=$MONGO_URI" >> .env && \
    echo "JWT_SECRET=$JWT_SECRET" >> .env && \
    echo "CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME" >> .env && \
    echo "CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY" >> .env && \
    echo "CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET" >> .env

EXPOSE 3000

CMD ["node", "server.js"]
